# Generated by Django 4.2.7 on 2025-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='criminal_record_file',
            field=models.FileField(blank=True, upload_to='teacher_criminal_records/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='diploma_file',
            field=models.FileField(blank=True, upload_to='teacher_diplomas/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='identity_document_file',
            field=models.FileField(blank=True, upload_to='teacher_identity/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='teacher_photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='proof_of_address_file',
            field=models.FileField(blank=True, upload_to='teacher_address/'),
        ),
    ]
