# Generated by Django 4.2.7 on 2025-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courseavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseavailability',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
