# Generated by Django 5.2.7 on 2025-10-11 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courseavailability_specific_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur (hex)')),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Tag de contenu',
                'verbose_name_plural': 'Tags de contenu',
                'db_table': 'content_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('content_type', models.CharField(choices=[('course', 'Cours'), ('video', 'Capsule Vidéo'), ('pdf', 'Document PDF'), ('manual', 'Manuel'), ('qcm', 'QCM/Quiz'), ('exercise', 'Exercice'), ('lesson', 'Leçon')], max_length=20, verbose_name='Type de contenu')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathématiques'), ('physics', 'Physique'), ('chemistry', 'Chimie'), ('biology', 'Biologie'), ('french', 'Français'), ('english', 'Anglais'), ('history', 'Histoire'), ('geography', 'Géographie'), ('philosophy', 'Philosophie'), ('computer_science', 'Informatique'), ('economics', 'Économie'), ('sports', 'Éducation Physique')], max_length=50, verbose_name='Matière')),
                ('class_level', models.CharField(choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', '2nde'), ('1ere', '1ère'), ('terminale', 'Terminale'), ('university', 'Université')], max_length=20, verbose_name='Classe')),
                ('country', models.CharField(choices=[('cameroon', 'Cameroun'), ('france', 'France'), ('senegal', 'Sénégal'), ('ivory_coast', "Côte d'Ivoire"), ('mali', 'Mali'), ('burkina_faso', 'Burkina Faso'), ('niger', 'Niger'), ('chad', 'Tchad'), ('gabon', 'Gabon'), ('congo', 'Congo'), ('dr_congo', 'RDC'), ('central_africa', 'Centrafrique'), ('benin', 'Bénin'), ('togo', 'Togo'), ('guinea', 'Guinée'), ('madagascar', 'Madagascar'), ('mauritius', 'Maurice'), ('morocco', 'Maroc'), ('algeria', 'Algérie'), ('tunisia', 'Tunisie')], max_length=50, verbose_name='Pays')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='Niveau de difficulté')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('file_size_mb', models.FloatField(blank=True, null=True, verbose_name='Taille du fichier (MB)')),
                ('file_format', models.CharField(blank=True, max_length=20, verbose_name='Format du fichier')),
                ('content_file', models.FileField(blank=True, null=True, upload_to='educational_content/', verbose_name='Fichier de contenu')),
                ('video_url', models.URLField(blank=True, verbose_name='URL vidéo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='content_thumbnails/', verbose_name='Miniature')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Contenu en vedette')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('download_count', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('rating_average', models.FloatField(default=0.0, verbose_name='Note moyenne')),
                ('rating_count', models.IntegerField(default=0, verbose_name="Nombre d'évaluations")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('keywords', models.JSONField(default=list, verbose_name='Mots-clés')),
                ('learning_objectives', models.JSONField(default=list, verbose_name="Objectifs d'apprentissage")),
                ('prerequisites', models.JSONField(default=list, verbose_name='Prérequis')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contents', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Contenu pédagogique',
                'verbose_name_plural': 'Contenus pédagogiques',
                'db_table': 'educational_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.educationalcontent', verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Évaluation de contenu',
                'verbose_name_plural': 'Évaluations de contenu',
                'db_table': 'content_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre du QCM')),
                ('description', models.TextField(verbose_name='Description')),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True, verbose_name='Limite de temps (minutes)')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Nombre maximum de tentatives')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Score de réussite (%)')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='Afficher les bonnes réponses')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='Mélanger les questions')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Total des tentatives')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Score moyen')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='Taux de réussite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_sets', to='core.educationalcontent', verbose_name='Contenu associé')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'QCM',
                'verbose_name_plural': 'QCMs',
                'db_table': 'qcm_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCMQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Texte de la question')),
                ('question_type', models.CharField(choices=[('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('true_false', 'Vrai/Faux'), ('text', 'Réponse libre')], default='single_choice', max_length=20, verbose_name='Type de question')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('points', models.IntegerField(default=1, verbose_name='Points')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=20, verbose_name='Difficulté')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qcm_images/', verbose_name='Image')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='qcm_audio/', verbose_name='Fichier audio')),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.qcm', verbose_name='QCM')),
            ],
            options={
                'verbose_name': 'Question QCM',
                'verbose_name_plural': 'Questions QCM',
                'db_table': 'qcm_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QCMAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(verbose_name='Texte de la réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.qcmquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse QCM',
                'verbose_name_plural': 'Réponses QCM',
                'db_table': 'qcm_answers',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['content_type'], name='educational_content_87388b_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['subject'], name='educational_subject_c5d97c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['class_level'], name='educational_class_l_ff116e_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['country'], name='educational_country_df8332_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['status'], name='educational_status_db1811_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['created_by'], name='educational_created_68dbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['-created_at'], name='educational_created_ec11f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentrating',
            unique_together={('content', 'user')},
        ),
    ]
