# Generated by Django 5.2.7 on 2025-10-19 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contenttag_educationalcontent_contentrating_qcm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='certification_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_schedule',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='professional_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='availability_for_adults',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_account_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cancellation_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='languages_spoken',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='payment_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reliability_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_cancellations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_level',
            field=models.CharField(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('adult', 'Adulte')], max_length=20),
        ),
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ban_reason', models.CharField(choices=[('fraud', 'Fraude'), ('inappropriate_behavior', 'Comportement inapproprié'), ('payment_issues', 'Problèmes de paiement'), ('safety_violation', 'Violation de sécurité'), ('terms_violation', 'Violation des conditions'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_addresses', models.JSONField(default=list)),
                ('email_patterns', models.JSONField(default=list)),
                ('device_fingerprints', models.JSONField(default=list)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur banni',
                'verbose_name_plural': 'Utilisateurs bannis',
                'db_table': 'banned_users',
                'ordering': ['-banned_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('inappropriate_behavior', 'Comportement inapproprié'), ('professional_misconduct', 'Faute professionnelle'), ('cancellation_issues', "Problèmes d'annulation"), ('payment_dispute', 'Litige de paiement'), ('safety_concern', 'Préoccupation de sécurité'), ('other', 'Autre')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('investigating', "En cours d'enquête"), ('resolved', 'Résolu'), ('dismissed', 'Rejeté'), ('escalated', 'Escaladé')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('booking_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('session_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='core.teacher')),
            ],
            options={
                'verbose_name': "Signalement d'incident",
                'verbose_name_plural': "Signalements d'incidents",
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('payout_frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('on_demand', 'À la demande')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
                'db_table': 'payment_configurations',
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('duplicate_email', 'Email dupliqué'), ('suspicious_ip', 'Adresse IP suspecte'), ('banned_user_return', 'Utilisateur banni qui revient'), ('multiple_accounts', 'Comptes multiples'), ('suspicious_behavior', 'Comportement suspect'), ('payment_fraud', 'Fraude de paiement')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('investigating', "En cours d'enquête"), ('resolved', 'Résolu'), ('false_positive', 'Faux positif')], default='active', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de sécurité',
                'verbose_name_plural': 'Alertes de sécurité',
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Paiement enseignant',
                'verbose_name_plural': 'Paiements enseignants',
                'db_table': 'teacher_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('comment', models.TextField(blank=True)),
                ('teaching_quality', models.IntegerField(blank=True, choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], null=True)),
                ('punctuality', models.IntegerField(blank=True, choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], null=True)),
                ('communication', models.IntegerField(blank=True, choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], null=True)),
                ('professionalism', models.IntegerField(blank=True, choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Évaluation enseignant',
                'verbose_name_plural': 'Évaluations enseignants',
                'db_table': 'teacher_ratings',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student', 'session')},
            },
        ),
    ]
