# Generated by Django 5.2.7 on 2025-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_budget_range_student_certification_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Élève'), ('teacher', 'Enseignant'), ('author', 'Auteur'), ('parent', 'Parent'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], default='student', max_length=20),
        ),
    ]
